config/routes.rb
RedisOnRails::Application.routes.draw do
  devise_for :attendees

  resources :tutorials

  resources :talks

  resources :attendees do
    resource :following, only: [:create, :show, :destroy]
  end
  resources :conferences
  resource :notes
  resource :registrations

  root :to => 'conferences#index'

  if Rails.env.development?
    post '/callbacks', to: lambda { |env| [200, {"Content-Type" => "text/html"}, ["OK"]] }
  end

end

app/models/talk.rb
class Talk < ActiveRecord::Base
  include RedisProps

  attr_accessible :conference_id, :talk_name

  props "talk" do
    define :name, default: "Talk Name"
  end
end

app/controllers/talks_controller.rb
class TalksController < InheritedResources::Base
	expose(:events) { [] }
end

app/views/talks/_form.html.erb
<%= form_for(@talk) do |f| %>
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talk.errors.count, "error") %> prohibited this talk from being saved:</h2>

      <ul>
      <% @talk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :talk_name %><br />
    <%= f.number_field :talk_name %><br />
    <%= f.label :conference_id %><br />
    <%= f.number_field :conference_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/talks/edit.html.erb
<h1>Editing talk</h1>

<%= render 'form' %>

<%= link_to 'Show', @talk %> |
<%= link_to 'Back', talks_path %>

app/views/talks/index.html.erb
<h1>Listing talks</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

<% @talks.each do |talk| %>
  <tr>
    <td><%= link_to talk.talk_name, talk %></td>
    <td><%= link_to 'Edit', edit_talk_path(talk) %></td>
    <td><%= link_to 'Destroy', talk, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Talk', new_talk_path %>

app/views/talks/new.html.erb
<h1>New talk</h1>

<%= render 'form' %>

<%= link_to 'Back', talks_path %>

app/views/talks/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @talk.talk_name %></h1>
<p>
  <b>Conference:</b>
  <%= @talk.conference_id %>
</p>


<%= link_to 'Edit', edit_talk_path(@talk) %> |
<%= link_to 'Back', talks_path %>