config/routes.rb
RedisOnRails::Application.routes.draw do
  devise_for :attendees

  resources :tutorials

  resources :talks

  resources :attendees do
    resource :following, only: [:create, :show, :destroy]
  end
  resources :conferences
  resource :notes
  resource :registrations

  root :to => 'conferences#index'

  if Rails.env.development?
    post '/callbacks', to: lambda { |env| [200, {"Content-Type" => "text/html"}, ["OK"]] }
  end

end

app/models/conference.rb
class Conference < ActiveRecord::Base
  #include Redis::Objects
  #value :location
  attr_accessible :name;

  default_scope lambda { order('name asc') }

  has_many :talks
  has_many :tutorials

  # gotcha note.. consumers might try to << attendees
  def attendees
    # Attendee.find(rdb[:attendee_ids])
    Attendee.find_all_by_id(rdb[:attendee_ids].smembers)
  end

  def self.events
    Event.where(id: rdb[:events].zrange(0, -1))
  end

  def location
    rdb[:location].get
  end
  
  def location=(loc)
    rdb[:location].set loc
  end

  def register(attendee)  
    Redis.current.multi do
      rdb[:attendee_ids].sadd(attendee.id)
      attendee.rdb[:conference_ids].sadd id
    end
    AttendeeRegisteredEvent.create(attendee: attendee,
       conference: self, description: "#{attendee.name} registered for #{name}")
  end

  def registered?(attendee)
    rdb[:attendee_ids].sismember(attendee.id)
  end

  def unregister(attendee)
    Redis.current.multi do
      rdb[:attendee_ids].srem(attendee.id)
      attendee.rdb[:conference_ids].srem id
    end
    AttendeeUnregisteredEvent.create(attendee: attendee,
       conference: self, description: "#{attendee.name} unregistered from #{name}")
  end

  def notes_for(attendee)
    rdb[:notes].hget(attendee.id)
  end
  
  def set_notes_for(attendee, text)
    rdb[:notes].hset(attendee.id, text)
    AttendeeNotesUpdatedEvent.create(attendee: attendee,
      conference: self, description: "#{attendee.name} updated his notes for #{name}")
  end

  def to_s
    name
  end

  # protected
  # 
  # def after_create
  #   ConferenceCreatedEvent.create(conference: self, description: "#{name} was added to the site")
  # end
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  expose(:conference)
  expose(:events) do
    #current_attendee ? current_attendee.events(conference) : (Conference.events)
    Event.where(id: Redis.current.zrange(:events, -6, -1))
    #Event.all
  end

  # def toggle_filter
  #   current_attendee.rdb[:filter][conference] = !current_attendee.rdb[:filter][conference]
  # end
end

app/views/conferences/index.html.haml
%td
  %ul
    - Conference.all.each do |conf|
      %li
        %strong= link_to conf.name, conference_path(conf)
        .location= conf.location
        - if current_attendee
          - if current_attendee.registered_for?(conf)
            = link_to 'Unregister', registrations_path(conference_id: conf.id), method: :delete
          - else
            = link_to 'Register', registrations_path(conference_id: conf.id), method: :post

%td
  %ul= render partial: "event", collection: events

app/views/conferences/show.html.haml
%td
  %h2= conference.name
  - if current_attendee
    - if current_attendee.registered_for?(conference)
      = link_to 'Unregister', registrations_path(conference_id: conference.id), method: :delete
    - else
      = link_to 'Register', registrations_path(conference_id: conference.id), method: :post

  %h3 Attendees
  %ul.attendees
    - conference.attendees.each do |a|
      %li= link_to image_tag(a.gravatar_url, size: "80x80", title: a.name), attendee_path(a)

  - if current_attendee
    %h3 My Notes
    = semantic_form_for :notes, url: notes_path(conference_id: conference.id), method: :put do |f|
      = f.inputs do
        = f.input :text, as: :text, label: "", input_html: { value: conference.notes_for(current_attendee) }
        = f.submit

%td
  %ul= render partial: "event", collection: events