config/routes.rb
RedisOnRails::Application.routes.draw do
  devise_for :attendees

  resources :tutorials

  resources :talks

  resources :attendees do
    resource :following, only: [:create, :show, :destroy]
  end
  resources :conferences
  resource :notes
  resource :registrations

  root :to => 'conferences#index'

  if Rails.env.development?
    post '/callbacks', to: lambda { |env| [200, {"Content-Type" => "text/html"}, ["OK"]] }
  end

end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  #include Redis::Objects
  
  belongs_to :presenter  
  #counter :seats_taken

  # def signup(attendee)
  #   seats_taken.increment do |count|
  #     if count < max_attendees
  #       rdb[:attendee_ids].sadd(attendee.id)
  #       # sadd returns true if successfully added id
  #       # and returns false if already existed, which makes the counter rollback
  #     end
  #     # nil also makes the counter rollback
  #   end
  # end
end

app/controllers/tutorials_controller.rb
class TutorialsController < InheritedResources::Base
end

app/views/tutorials/_form.html.erb
<%= form_for(@tutorial) do |f| %>
  <% if @tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>

      <ul>
      <% @tutorial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :conference_id %><br />
    <%= f.number_field :conference_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tutorials/edit.html.erb
<h1>Editing tutorial</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutorial %> |
<%= link_to 'Back', tutorials_path %>

app/views/tutorials/index.html.erb
<h1>Listing tutorials</h1>

<table>
  <tr>
    <th>Conference</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tutorials.each do |tutorial| %>
  <tr>
    <td><%= tutorial.conference_id %></td>
    <td><%= link_to 'Show', tutorial %></td>
    <td><%= link_to 'Edit', edit_tutorial_path(tutorial) %></td>
    <td><%= link_to 'Destroy', tutorial, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tutorial', new_tutorial_path %>

app/views/tutorials/new.html.erb
<h1>New tutorial</h1>

<%= render 'form' %>

<%= link_to 'Back', tutorials_path %>

app/views/tutorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Conference:</b>
  <%= @tutorial.conference_id %>
</p>


<%= link_to 'Edit', edit_tutorial_path(@tutorial) %> |
<%= link_to 'Back', tutorials_path %>