config/routes.rb
RedisOnRails::Application.routes.draw do
  devise_for :attendees

  resources :tutorials

  resources :talks

  resources :attendees do
    resource :following, only: [:create, :show, :destroy]
  end
  resources :conferences
  resource :notes
  resource :registrations

  root :to => 'conferences#index'

  if Rails.env.development?
    post '/callbacks', to: lambda { |env| [200, {"Content-Type" => "text/html"}, ["OK"]] }
  end

end

app/views/layouts/application.html.haml
!!!!
%html{html_attrs(I18n.locale), class: page_class}
  %head
    %title Redis on Rails Example App
    - if protect_against_forgery?
      %meta(name='authenticity_token' content=form_authenticity_token)
    = csrf_meta_tag

    = javascript_include_tag 'jquery.min.js'
    = javascript_include_tag 'jquery-ui-1.8.17.custom.min.js'
    = javascript_include_tag 'application'

    = stylesheet_link_tag 'conferences'

  %body
    #messages
      - unless flash.empty?
        - flash.each do |name, msg|
          - next unless [:alert, :error, :notice].include?(name)
          %p.flash_message{id: name}
            = msg
          %script
            $('#messages').delay(2000).fadeOut('slow');

    .header{colspan: 2}
      - if attendee_signed_in?
        Signed in as #{current_attendee.email}
        [
        = link_to 'x', destroy_attendee_session_path, method: 'delete'
        ]
      - else
        = link_to 'Sign in', new_attendee_session_path
    %table
      %tr
        %td{colspan: 2}
          %h1= link_to "Conferences Sample App", root_path
      %tr.main
        = yield
    #footer
      Prepared for RailsConf2012 by
      = link_to "Obie Fernandez", "http://blog.obiefernandez.com"
      |
      = link_to "Source", "https://github.com/obie/redis_on_rails"